---
- name: Ensure created root directory
  file:
    path: "{{ releases_path }}"
    owner: "{{ releases_owner }}"
    group: "{{ releases_group }}"
    mode: 0755
    state: directory
  tags: always

- name: Ensure base content
  copy:
    src: "{{ releases_content.root + releases_content.path }}"
    dest: "{{ releases_path + '/' }}"
    owner: "{{ releases_owner }}"
    group: "{{ releases_group }}"
    mode: preserve
  loop: "{{ query('filetree', releases_base) | default('[]') | to_json | from_json | json_query('[?!(contains(path, `/`))]') }}"
  loop_control:
    loop_var: releases_content
    label: "{{ releases_content.path }}"
  tags: always

- name: Run preparation tasks
  import_tasks: prepare.yml
  tags:
    - never
    - prepare

- name: Run release tasks
  import_tasks: release.yml
  tags:
    - never
    - release
