---
- name: Ensure created root directory
  file:
    path: "{{ releases_path }}"
    owner: "{{ ansible_user }}"
    group: www-data
    mode: 0755
    state: directory

- name: Ensure base content
  copy:
    src: "{{ releases_content.root + releases_content.path }}"
    dest: "{{ releases_path + releases_content.path }}"
    owner: "{{ ansible_user }}"
    group: www-data
    mode: preserve
  loop: "{{ lookup('filetree', releases_base) | default('[]') }}"
  loop_control:
    loop_var: releases_content
    label: "{{ releases_content.path }}"

- name: Run preparation tasks
  include_tasks: prepare.yml
  tags:
    - never
    - prepare

- name: Run release tasks
  include_tasks: release.yml
  tags:
    - never
    - release
